apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: byscane-nightly
spec:
  schedule: "0 */2 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          containers:
          - name: schedule
            image: elek/ozone-schedule
            args:
              - argo
              - submit
              - -p
              - notify=true
              - -p
              - branch=ozone-0.4.1
              - /tmp/ozone-build.yaml
              - --generate-name=byscane-nightly-
