apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: klepif
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      backoffLimit: 1
      template:
        metadata:
           labels:
              component: klepif
        spec:
          restartPolicy: Never
          containers:
          - name: schedule
            imagePullPolicy: Always
            image: elek/ozone-schedule
            args:
              - klepif
              - check
            env:
            - name: KLEPIF_CONFIG_DIR
              value: /git/argo-ozone
            - name: KLEPIF_GITHUB_TOKEN
              valueFrom:
                secretKeyRef:
                  name: github-token
                  key: secret
            volumeMounts:
            - name: cache
              mountPath: /cache
            - mountPath: /git
              name: build-def
          volumes:
          - name: cache
            persistentVolumeClaim:
               claimName: ozone-klepif
          - name: build-def
            gitRepo:
              repository: "https://github.com/elek/argo-ozone.git"
              revision: "master"
