apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ozone-klepif
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: standard
  selector:
    matchLabels:
      instance: ozone-klepif
