apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: hdds1735-unit
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: schedule
            image: elek/ozone-schedule
            args:
              - limit.sh
              - -p
              - job=branch=HDDS-1735
              - /tmp/ozone-build.yaml
              - --generate-name=hdds1735-
              - --entrypoint=run-unit
            env:
                - name: ARGO_NAME
                  value: hdds1735
          restartPolicy: OnFailure
