apiVersion: batch/v1
kind: Job
metadata:
  name: job-test
spec:
      template:
        spec:
          restartPolicy: Never
          containers:
          - name: schedule
            image: elek/ozone-schedule
            args:
              - bash
              - -c
              - argo submit -p notify=false -p org=elek -p branch=check-report /git/argo-ozone/ozone-build.yaml --generate-name=dev-check-$(date '+%Y%m%d')- --entrypoint=run-checkstyle
            volumeMounts:
            - mountPath: /git
              name: build-def
          volumes:
          - name: build-def
            gitRepo:
              repository: "https://github.com/elek/argo-ozone.git"
              revision: "master"
