apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: trunk-performance-nightly
spec:
  schedule: "0 0 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          containers:
          - name: schedule
            image: elek/ozone-schedule
            args:
              - argo submit /git/argo-ozone/ozone-deploy.yaml --generate-name=performance-nightly-$(date '+%Y%m%d')-
            volumeMounts:
            - mountPath: /git
              name: build-def
          volumes:
          - name: build-def
            gitRepo:
              repository: "https://github.com/elek/argo-ozone.git"
              revision: "master"
